FROM python:3.7.7-slim-buster

ENV USER_HOME=/home/appuser
ENV APP_HOME=/home/appuser/app

# set up non-root user
RUN useradd --create-home appuser && mkdir $APP_HOME

WORKDIR $APP_HOME

# extra packages from extra-packages.sh
COPY ./app/extra-packages.sh $APP_HOME/
RUN chmod +x extra-packages.sh && ./extra-packages.sh

# upgrade pip and install requirements
COPY ./app/requirements.txt $APP_HOME/
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# copy all app files
ADD app $APP_HOME
COPY wsgi.py $USER_HOME

RUN chown -R appuser:appuser $APP_HOME

# give run permission
RUN chmod +x ./entrypoint.dev.sh

# switch to non-root user
RUN usermod -aG adm appuser
USER appuser

WORKDIR $USER_HOME

# call cmd script
CMD ["./entrypoint.dev.sh"]
